name: ReportSystem
version: ${project.version}
main: net.casheh.reportsystem.ReportSystem
authors: [ Cashless ]
description: A system used to report players, requested by Extensy.
commands:
  report:
  reports: